### ISSUE TITLE
How to configure transpilation

### ISSUE THREAD

**Issue by pfosser** [lgrignon/jsweet-gradle-plugin#12]
Hi,
  good work with the plugin but, please forgive me if I'm wrong, I found no way to configure the transpiler (through the jsweetconfig.json) except when such file is in the very same directory the task is executed from. That can be easily arranged when doing a manual build but it is harder, e.g., in an Eclipse build. As a matter of fact, the transpiler looks for the file in my home dir when the task is executed from Eclipse (equipped with the Buildship tooling).
Now I'm a gradle newbie and I don't know if things can be set up to work in Eclipse too. Could you give me any hint?
Tia,
Paolo

**Comment by lgrignon** [comment]
Hello @pfosser, thank you for your feedback.
If you want to use JSweet under Eclipse, aren't you looking for https://github.com/cincheo/jsweet-eclipse-plugin ?
IMHO, I prefer to use the JSweet maven plugin, because it has a watch option, which is ideal for development mode, and it fits perfectly into CI or Eclipse launch configurations as well. It also has more options to configure the working directory. 

That being said, you should be able to use the Gradle plugin with no problem, even in Eclipse. 
I don't understand what you want to do, the jsweetconfig.json file is supposed to be in your project's directory, but it seems that you want to put this file in a different location, am I right? Or maybe I misunderstood and you want to build your project from another directory. For the latter case, I might have a solution, which I already had to integrate into the maven plugin.
I hope I got this right :)

Thanks again for your feedback
